version: '3'
services:
  web:
    env_file: web.env
    build:
      context: .
      dockerfile: $dockerfile
      args:
        UID: $UID
    volumes:
      - .:/home/docker/src
    ports:
      - "8080-8081"
    environment:
      - REDIS_URL=redis://localhost:6379
      - LAM_OAUTH_PRIVATE_KEY=$LAM_OAUTH_PRIVATE_KEY
    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"
