version: '3'
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: $UID
    environment:
      - PORT=8080
      - HMR_PORT=8081
      - HOST=127.0.0.1
    depends_on:
      - redis-dev
    volumes:
      - .:/home/docker/src
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis-dev:6379
      - LAM_OAUTH_PRIVATE_KEY
    stdin_open: true
    tty: true
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - HOST=0.0.0.0.1
    ports:
      - "8080:8080"
    environment:
      - LAM_OAUTH_PRIVATE_KEY
  redis-dev:
    image: "redis:alpine"
