version: 2
jobs:
  build_and_deploy:
    docker:
      - image: docker:18.09
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache --no-progress bash curl make nodejs
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: make deploy
workflows:
  version: 2
  ci:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
